name: Deploy Docsify to GitHub Pages

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - '.github/workflows/pages.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Docsify setup
        run: |
          echo "Validating Docsify configuration..."
          if [ ! -f "docs/index.html" ]; then
            echo "❌ docs/index.html not found"
            exit 1
          fi
          if [ ! -f "docs/_sidebar.md" ]; then
            echo "❌ docs/_sidebar.md not found"
            exit 1
          fi
          if [ ! -f "docs/README.md" ]; then
            echo "❌ docs/README.md not found"
            exit 1
          fi
          echo "✅ Docsify configuration is valid"

      - name: Verify documentation structure
        run: |
          echo "Verifying documentation structure..."
          find docs -name "*.md" -type f | head -10
          echo "✅ Documentation structure verified"

      - name: Upload Pages artifact
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4